using System.Text;

namespace Peony.Core;

/// <summary>
/// Generates platform-specific hardware register include files for .pasm projects.
/// Each platform gets a .inc file with named constants for all I/O registers.
/// </summary>
public static class HardwareIncludeGenerator {
	public static string Generate(string platform) {
		return platform.ToLowerInvariant() switch {
			"nes" => GenerateNes(),
			"snes" or "super nes" => GenerateSnes(),
			"game boy" or "gameboy" or "gb" => GenerateGameBoy(),
			"game boy advance" or "gba" => GenerateGba(),
			"atari 2600" or "atari2600" or "a26" => GenerateAtari2600(),
			"atari lynx" or "lynx" => GenerateLynx(),
			_ => GenerateGeneric(platform)
		};
	}

	private static string GenerateNes() {
		var sb = new StringBuilder();
		sb.AppendLine("; NES Hardware Registers");
		sb.AppendLine("; Generated by Peony");
		sb.AppendLine();

		sb.AppendLine("; PPU Registers ($2000-$2007)");
		sb.AppendLine("PPU_CTRL    = $2000");
		sb.AppendLine("PPU_MASK    = $2001");
		sb.AppendLine("PPU_STATUS  = $2002");
		sb.AppendLine("OAM_ADDR    = $2003");
		sb.AppendLine("OAM_DATA    = $2004");
		sb.AppendLine("PPU_SCROLL  = $2005");
		sb.AppendLine("PPU_ADDR    = $2006");
		sb.AppendLine("PPU_DATA    = $2007");
		sb.AppendLine();

		sb.AppendLine("; APU Registers ($4000-$4017)");
		sb.AppendLine("SQ1_VOL     = $4000");
		sb.AppendLine("SQ1_SWEEP   = $4001");
		sb.AppendLine("SQ1_LO      = $4002");
		sb.AppendLine("SQ1_HI      = $4003");
		sb.AppendLine("SQ2_VOL     = $4004");
		sb.AppendLine("SQ2_SWEEP   = $4005");
		sb.AppendLine("SQ2_LO      = $4006");
		sb.AppendLine("SQ2_HI      = $4007");
		sb.AppendLine("TRI_LINEAR  = $4008");
		sb.AppendLine("TRI_LO      = $400a");
		sb.AppendLine("TRI_HI      = $400b");
		sb.AppendLine("NOISE_VOL   = $400c");
		sb.AppendLine("NOISE_LO    = $400e");
		sb.AppendLine("NOISE_HI    = $400f");
		sb.AppendLine("DMC_FREQ    = $4010");
		sb.AppendLine("DMC_RAW     = $4011");
		sb.AppendLine("DMC_START   = $4012");
		sb.AppendLine("DMC_LEN     = $4013");
		sb.AppendLine("OAM_DMA     = $4014");
		sb.AppendLine("SND_CHN     = $4015");
		sb.AppendLine("JOY1        = $4016");
		sb.AppendLine("JOY2        = $4017");

		return sb.ToString();
	}

	private static string GenerateSnes() {
		var sb = new StringBuilder();
		sb.AppendLine("; SNES Hardware Registers");
		sb.AppendLine("; Generated by Peony");
		sb.AppendLine();

		sb.AppendLine("; PPU Registers ($2100-$2133)");
		sb.AppendLine("INIDISP     = $2100");
		sb.AppendLine("OBSEL       = $2101");
		sb.AppendLine("OAMADDL     = $2102");
		sb.AppendLine("OAMADDH     = $2103");
		sb.AppendLine("OAMDATA     = $2104");
		sb.AppendLine("BGMODE      = $2105");
		sb.AppendLine("MOSAIC      = $2106");
		sb.AppendLine("BG1SC       = $2107");
		sb.AppendLine("BG2SC       = $2108");
		sb.AppendLine("BG3SC       = $2109");
		sb.AppendLine("BG4SC       = $210a");
		sb.AppendLine("BG12NBA     = $210b");
		sb.AppendLine("BG34NBA     = $210c");
		sb.AppendLine("BG1HOFS     = $210d");
		sb.AppendLine("BG1VOFS     = $210e");
		sb.AppendLine("BG2HOFS     = $210f");
		sb.AppendLine("BG2VOFS     = $2110");
		sb.AppendLine("BG3HOFS     = $2111");
		sb.AppendLine("BG3VOFS     = $2112");
		sb.AppendLine("BG4HOFS     = $2113");
		sb.AppendLine("BG4VOFS     = $2114");
		sb.AppendLine("VMAIN       = $2115");
		sb.AppendLine("VMADDL      = $2116");
		sb.AppendLine("VMADDH      = $2117");
		sb.AppendLine("VMDATAL     = $2118");
		sb.AppendLine("VMDATAH     = $2119");
		sb.AppendLine("M7SEL       = $211a");
		sb.AppendLine("M7A         = $211b");
		sb.AppendLine("M7B         = $211c");
		sb.AppendLine("M7C         = $211d");
		sb.AppendLine("M7D         = $211e");
		sb.AppendLine("M7X         = $211f");
		sb.AppendLine("M7Y         = $2120");
		sb.AppendLine("CGADD       = $2121");
		sb.AppendLine("CGDATA      = $2122");
		sb.AppendLine("W12SEL      = $2123");
		sb.AppendLine("W34SEL      = $2124");
		sb.AppendLine("WOBJSEL     = $2125");
		sb.AppendLine("WH0         = $2126");
		sb.AppendLine("WH1         = $2127");
		sb.AppendLine("WH2         = $2128");
		sb.AppendLine("WH3         = $2129");
		sb.AppendLine("WBGLOG      = $212a");
		sb.AppendLine("WOBJLOG     = $212b");
		sb.AppendLine("TM          = $212c");
		sb.AppendLine("TS          = $212d");
		sb.AppendLine("TMW         = $212e");
		sb.AppendLine("TSW         = $212f");
		sb.AppendLine("CGWSEL      = $2130");
		sb.AppendLine("CGADSUB     = $2131");
		sb.AppendLine("COLDATA     = $2132");
		sb.AppendLine("SETINI      = $2133");
		sb.AppendLine();

		sb.AppendLine("; CPU I/O Registers ($4200-$421f)");
		sb.AppendLine("NMITIMEN    = $4200");
		sb.AppendLine("WRIO        = $4201");
		sb.AppendLine("WRMPYA      = $4202");
		sb.AppendLine("WRMPYB      = $4203");
		sb.AppendLine("WRDIVL      = $4204");
		sb.AppendLine("WRDIVH      = $4205");
		sb.AppendLine("WRDIVB      = $4206");
		sb.AppendLine("HTIMEL      = $4207");
		sb.AppendLine("HTIMEH      = $4208");
		sb.AppendLine("VTIMEL      = $4209");
		sb.AppendLine("VTIMEH      = $420a");
		sb.AppendLine("MDMAEN      = $420b");
		sb.AppendLine("HDMAEN      = $420c");
		sb.AppendLine("MEMSEL      = $420d");
		sb.AppendLine("RDNMI       = $4210");
		sb.AppendLine("TIMEUP      = $4211");
		sb.AppendLine("HVBJOY      = $4212");
		sb.AppendLine("RDIO        = $4213");
		sb.AppendLine("RDDIVL      = $4214");
		sb.AppendLine("RDDIVH      = $4215");
		sb.AppendLine("RDMPYL      = $4216");
		sb.AppendLine("RDMPYH      = $4217");
		sb.AppendLine("JOY1L       = $4218");
		sb.AppendLine("JOY1H       = $4219");
		sb.AppendLine("JOY2L       = $421a");
		sb.AppendLine("JOY2H       = $421b");
		sb.AppendLine("JOY3L       = $421c");
		sb.AppendLine("JOY3H       = $421d");
		sb.AppendLine("JOY4L       = $421e");
		sb.AppendLine("JOY4H       = $421f");

		return sb.ToString();
	}

	private static string GenerateGameBoy() {
		var sb = new StringBuilder();
		sb.AppendLine("; Game Boy Hardware Registers");
		sb.AppendLine("; Generated by Peony");
		sb.AppendLine();

		sb.AppendLine("; LCD Registers ($ff40-$ff4b)");
		sb.AppendLine("LCDC        = $ff40");
		sb.AppendLine("STAT        = $ff41");
		sb.AppendLine("SCY         = $ff42");
		sb.AppendLine("SCX         = $ff43");
		sb.AppendLine("LY          = $ff44");
		sb.AppendLine("LYC         = $ff45");
		sb.AppendLine("DMA         = $ff46");
		sb.AppendLine("BGP         = $ff47");
		sb.AppendLine("OBP0        = $ff48");
		sb.AppendLine("OBP1        = $ff49");
		sb.AppendLine("WY          = $ff4a");
		sb.AppendLine("WX          = $ff4b");
		sb.AppendLine();

		sb.AppendLine("; Sound Registers ($ff10-$ff26)");
		sb.AppendLine("NR10        = $ff10");
		sb.AppendLine("NR11        = $ff11");
		sb.AppendLine("NR12        = $ff12");
		sb.AppendLine("NR13        = $ff13");
		sb.AppendLine("NR14        = $ff14");
		sb.AppendLine("NR21        = $ff16");
		sb.AppendLine("NR22        = $ff17");
		sb.AppendLine("NR23        = $ff18");
		sb.AppendLine("NR24        = $ff19");
		sb.AppendLine("NR30        = $ff1a");
		sb.AppendLine("NR31        = $ff1b");
		sb.AppendLine("NR32        = $ff1c");
		sb.AppendLine("NR33        = $ff1d");
		sb.AppendLine("NR34        = $ff1e");
		sb.AppendLine("NR41        = $ff20");
		sb.AppendLine("NR42        = $ff21");
		sb.AppendLine("NR43        = $ff22");
		sb.AppendLine("NR44        = $ff23");
		sb.AppendLine("NR50        = $ff24");
		sb.AppendLine("NR51        = $ff25");
		sb.AppendLine("NR52        = $ff26");
		sb.AppendLine();

		sb.AppendLine("; Timer Registers ($ff04-$ff07)");
		sb.AppendLine("DIV         = $ff04");
		sb.AppendLine("TIMA        = $ff05");
		sb.AppendLine("TMA         = $ff06");
		sb.AppendLine("TAC         = $ff07");
		sb.AppendLine();

		sb.AppendLine("; Interrupt Registers");
		sb.AppendLine("IF          = $ff0f");
		sb.AppendLine("IE          = $ffff");
		sb.AppendLine();

		sb.AppendLine("; Serial Registers");
		sb.AppendLine("SB          = $ff01");
		sb.AppendLine("SC          = $ff02");
		sb.AppendLine();

		sb.AppendLine("; Joypad");
		sb.AppendLine("JOYP        = $ff00");

		return sb.ToString();
	}

	private static string GenerateGba() {
		var sb = new StringBuilder();
		sb.AppendLine("; GBA Hardware Registers");
		sb.AppendLine("; Generated by Peony");
		sb.AppendLine();

		sb.AppendLine("; LCD Registers ($04000000-$04000056)");
		sb.AppendLine("DISPCNT     = $04000000");
		sb.AppendLine("DISPSTAT    = $04000004");
		sb.AppendLine("VCOUNT      = $04000006");
		sb.AppendLine("BG0CNT      = $04000008");
		sb.AppendLine("BG1CNT      = $0400000a");
		sb.AppendLine("BG2CNT      = $0400000c");
		sb.AppendLine("BG3CNT      = $0400000e");
		sb.AppendLine("BG0HOFS     = $04000010");
		sb.AppendLine("BG0VOFS     = $04000012");
		sb.AppendLine("BG1HOFS     = $04000014");
		sb.AppendLine("BG1VOFS     = $04000016");
		sb.AppendLine("BG2HOFS     = $04000018");
		sb.AppendLine("BG2VOFS     = $0400001a");
		sb.AppendLine("BG3HOFS     = $0400001c");
		sb.AppendLine("BG3VOFS     = $0400001e");
		sb.AppendLine("WIN0H       = $04000040");
		sb.AppendLine("WIN1H       = $04000042");
		sb.AppendLine("WIN0V       = $04000044");
		sb.AppendLine("WIN1V       = $04000046");
		sb.AppendLine("WININ       = $04000048");
		sb.AppendLine("WINOUT      = $0400004a");
		sb.AppendLine("BLDCNT      = $04000050");
		sb.AppendLine("BLDALPHA    = $04000052");
		sb.AppendLine("BLDY        = $04000054");
		sb.AppendLine();

		sb.AppendLine("; Sound Registers");
		sb.AppendLine("SOUND1CNT_L = $04000060");
		sb.AppendLine("SOUND1CNT_H = $04000062");
		sb.AppendLine("SOUND1CNT_X = $04000064");
		sb.AppendLine("SOUND2CNT_L = $04000068");
		sb.AppendLine("SOUND2CNT_H = $0400006c");
		sb.AppendLine("SOUND3CNT_L = $04000070");
		sb.AppendLine("SOUND3CNT_H = $04000072");
		sb.AppendLine("SOUND3CNT_X = $04000074");
		sb.AppendLine("SOUND4CNT_L = $04000078");
		sb.AppendLine("SOUND4CNT_H = $0400007c");
		sb.AppendLine("SOUNDCNT_L  = $04000080");
		sb.AppendLine("SOUNDCNT_H  = $04000082");
		sb.AppendLine("SOUNDCNT_X  = $04000084");
		sb.AppendLine("SOUNDBIAS   = $04000088");
		sb.AppendLine();

		sb.AppendLine("; DMA Registers");
		sb.AppendLine("DMA0SAD     = $040000b0");
		sb.AppendLine("DMA0DAD     = $040000b4");
		sb.AppendLine("DMA0CNT     = $040000b8");
		sb.AppendLine("DMA1SAD     = $040000bc");
		sb.AppendLine("DMA1DAD     = $040000c0");
		sb.AppendLine("DMA1CNT     = $040000c4");
		sb.AppendLine("DMA2SAD     = $040000c8");
		sb.AppendLine("DMA2DAD     = $040000cc");
		sb.AppendLine("DMA2CNT     = $040000d0");
		sb.AppendLine("DMA3SAD     = $040000d4");
		sb.AppendLine("DMA3DAD     = $040000d8");
		sb.AppendLine("DMA3CNT     = $040000dc");
		sb.AppendLine();

		sb.AppendLine("; Timer Registers");
		sb.AppendLine("TM0CNT_L    = $04000100");
		sb.AppendLine("TM0CNT_H    = $04000102");
		sb.AppendLine("TM1CNT_L    = $04000104");
		sb.AppendLine("TM1CNT_H    = $04000106");
		sb.AppendLine("TM2CNT_L    = $04000108");
		sb.AppendLine("TM2CNT_H    = $0400010a");
		sb.AppendLine("TM3CNT_L    = $0400010c");
		sb.AppendLine("TM3CNT_H    = $0400010e");
		sb.AppendLine();

		sb.AppendLine("; Input");
		sb.AppendLine("KEYINPUT    = $04000130");
		sb.AppendLine("KEYCNT      = $04000132");
		sb.AppendLine();

		sb.AppendLine("; Interrupt");
		sb.AppendLine("IE          = $04000200");
		sb.AppendLine("IF          = $04000202");
		sb.AppendLine("IME         = $04000208");

		return sb.ToString();
	}

	private static string GenerateAtari2600() {
		var sb = new StringBuilder();
		sb.AppendLine("; Atari 2600 TIA + RIOT Registers");
		sb.AppendLine("; Generated by Peony");
		sb.AppendLine();

		sb.AppendLine("; TIA Write Registers ($00-$2c)");
		sb.AppendLine("VSYNC       = $00");
		sb.AppendLine("VBLANK      = $01");
		sb.AppendLine("WSYNC       = $02");
		sb.AppendLine("RSYNC       = $03");
		sb.AppendLine("NUSIZ0      = $04");
		sb.AppendLine("NUSIZ1      = $05");
		sb.AppendLine("COLUP0      = $06");
		sb.AppendLine("COLUP1      = $07");
		sb.AppendLine("COLUPF      = $08");
		sb.AppendLine("COLUBK      = $09");
		sb.AppendLine("CTRLPF      = $0a");
		sb.AppendLine("REFP0       = $0b");
		sb.AppendLine("REFP1       = $0c");
		sb.AppendLine("PF0         = $0d");
		sb.AppendLine("PF1         = $0e");
		sb.AppendLine("PF2         = $0f");
		sb.AppendLine("RESP0       = $10");
		sb.AppendLine("RESP1       = $11");
		sb.AppendLine("RESM0       = $12");
		sb.AppendLine("RESM1       = $13");
		sb.AppendLine("RESBL       = $14");
		sb.AppendLine("AUDC0       = $15");
		sb.AppendLine("AUDC1       = $16");
		sb.AppendLine("AUDF0       = $17");
		sb.AppendLine("AUDF1       = $18");
		sb.AppendLine("AUDV0       = $19");
		sb.AppendLine("AUDV1       = $1a");
		sb.AppendLine("GRP0        = $1b");
		sb.AppendLine("GRP1        = $1c");
		sb.AppendLine("ENAM0       = $1d");
		sb.AppendLine("ENAM1       = $1e");
		sb.AppendLine("ENABL       = $1f");
		sb.AppendLine("HMP0        = $20");
		sb.AppendLine("HMP1        = $21");
		sb.AppendLine("HMM0        = $22");
		sb.AppendLine("HMM1        = $23");
		sb.AppendLine("HMBL        = $24");
		sb.AppendLine("VDELP0      = $25");
		sb.AppendLine("VDELP1      = $26");
		sb.AppendLine("VDELBL      = $27");
		sb.AppendLine("RESMP0      = $28");
		sb.AppendLine("RESMP1      = $29");
		sb.AppendLine("HMOVE       = $2a");
		sb.AppendLine("HMCLR       = $2b");
		sb.AppendLine("CXCLR       = $2c");
		sb.AppendLine();

		sb.AppendLine("; TIA Read Registers ($00-$0d)");
		sb.AppendLine("CXM0P       = $30");
		sb.AppendLine("CXM1P       = $31");
		sb.AppendLine("CXP0FB      = $32");
		sb.AppendLine("CXP1FB      = $33");
		sb.AppendLine("CXM0FB      = $34");
		sb.AppendLine("CXM1FB      = $35");
		sb.AppendLine("CXBLPF      = $36");
		sb.AppendLine("CXPPMM      = $37");
		sb.AppendLine("INPT0       = $38");
		sb.AppendLine("INPT1       = $39");
		sb.AppendLine("INPT2       = $3a");
		sb.AppendLine("INPT3       = $3b");
		sb.AppendLine("INPT4       = $3c");
		sb.AppendLine("INPT5       = $3d");
		sb.AppendLine();

		sb.AppendLine("; RIOT Registers ($280-$297)");
		sb.AppendLine("SWCHA       = $0280");
		sb.AppendLine("SWACNT      = $0281");
		sb.AppendLine("SWCHB       = $0282");
		sb.AppendLine("SWBCNT      = $0283");
		sb.AppendLine("INTIM       = $0284");
		sb.AppendLine("INSTAT      = $0285");
		sb.AppendLine("TIM1T       = $0294");
		sb.AppendLine("TIM8T       = $0295");
		sb.AppendLine("TIM64T      = $0296");
		sb.AppendLine("T1024T      = $0297");

		return sb.ToString();
	}

	private static string GenerateLynx() {
		var sb = new StringBuilder();
		sb.AppendLine("; Atari Lynx Hardware Registers");
		sb.AppendLine("; Generated by Peony");
		sb.AppendLine();

		sb.AppendLine("; Mikey ($fd00-$fdff)");
		sb.AppendLine("TIMER0      = $fd00");
		sb.AppendLine("TIMER1      = $fd04");
		sb.AppendLine("TIMER2      = $fd08");
		sb.AppendLine("TIMER3      = $fd0c");
		sb.AppendLine("TIMER4      = $fd10");
		sb.AppendLine("TIMER5      = $fd14");
		sb.AppendLine("TIMER6      = $fd18");
		sb.AppendLine("TIMER7      = $fd1c");
		sb.AppendLine("AUD0VOL     = $fd20");
		sb.AppendLine("AUD0SHFTFB  = $fd21");
		sb.AppendLine("AUD0OUTVAL  = $fd22");
		sb.AppendLine("AUD0L8SHFT  = $fd23");
		sb.AppendLine("AUD0TBACK   = $fd24");
		sb.AppendLine("AUD0CTL     = $fd25");
		sb.AppendLine("AUD0COUNT   = $fd26");
		sb.AppendLine("AUD0MISC    = $fd27");
		sb.AppendLine("MSTEREO     = $fd50");
		sb.AppendLine("INTRST      = $fd80");
		sb.AppendLine("INTSET      = $fd81");
		sb.AppendLine("MAPTS       = $fd84");
		sb.AppendLine("MPAN        = $fd8c");
		sb.AppendLine("SYSCTL1     = $fd87");
		sb.AppendLine("MIKEYHREV   = $fd88");
		sb.AppendLine("MIKEYSREV   = $fd89");
		sb.AppendLine("IODIR       = $fd8a");
		sb.AppendLine("IODAT       = $fd8b");
		sb.AppendLine("SERCTL      = $fd8c");
		sb.AppendLine("SERDAT      = $fd8d");
		sb.AppendLine("SDONEACK    = $fd90");
		sb.AppendLine("CPUSLEEP    = $fd91");
		sb.AppendLine("DISPCTL     = $fd92");
		sb.AppendLine("PBKUP       = $fd93");
		sb.AppendLine("DISPADR     = $fd94");
		sb.AppendLine("GREEN0      = $fda0");
		sb.AppendLine("BLUERED0    = $fdb0");
		sb.AppendLine();

		sb.AppendLine("; Suzy ($fc00-$fcff)");
		sb.AppendLine("TMPADRL     = $fc00");
		sb.AppendLine("TMPADRH     = $fc01");
		sb.AppendLine("TILTACUML   = $fc02");
		sb.AppendLine("TILTACUMH   = $fc03");
		sb.AppendLine("HOFF        = $fc04");
		sb.AppendLine("VOFF        = $fc06");
		sb.AppendLine("VIDBAS      = $fc08");
		sb.AppendLine("COLLBAS     = $fc0a");
		sb.AppendLine("VIDADRL     = $fc0c");
		sb.AppendLine("VIDADRH     = $fc0d");
		sb.AppendLine("COLLADRL    = $fc0e");
		sb.AppendLine("COLLADRH    = $fc0f");
		sb.AppendLine("SCBNEXT     = $fc10");
		sb.AppendLine("SPRDLINE    = $fc12");
		sb.AppendLine("HPOSSTRT    = $fc14");
		sb.AppendLine("VPOSSTRT    = $fc16");
		sb.AppendLine("SPRINIT     = $fc18");
		sb.AppendLine("SUZYHREV    = $fc88");
		sb.AppendLine("SUZYSREV    = $fc89");
		sb.AppendLine("SUZYBUSEN   = $fc90");
		sb.AppendLine("SPRGO       = $fc91");
		sb.AppendLine("SPRSYS      = $fc92");
		sb.AppendLine("JOYSTICK    = $fcb0");
		sb.AppendLine("SWITCHES    = $fcb1");
		sb.AppendLine("RCART0      = $fcb2");
		sb.AppendLine("RCART1      = $fcb3");
		sb.AppendLine("LEDS        = $fcc0");
		sb.AppendLine("PPORTSTAT   = $fcc2");
		sb.AppendLine("PPORTDATA   = $fcc3");
		sb.AppendLine("MATHD       = $fc52");
		sb.AppendLine("MATHC       = $fc53");
		sb.AppendLine("MATHB       = $fc54");
		sb.AppendLine("MATHA       = $fc55");
		sb.AppendLine("MATHP       = $fc56");
		sb.AppendLine("MATHN       = $fc57");
		sb.AppendLine("MATHE       = $fc60");
		sb.AppendLine("MATHM       = $fc61");
		sb.AppendLine("MATHH       = $fc62");
		sb.AppendLine("MATHG       = $fc63");
		sb.AppendLine("MATHF       = $fc64");

		return sb.ToString();
	}

	private static string GenerateGeneric(string platform) {
		var sb = new StringBuilder();
		sb.AppendLine($"; {platform} Hardware Registers");
		sb.AppendLine("; Generated by Peony");
		sb.AppendLine();
		sb.AppendLine("; No platform-specific registers defined.");
		sb.AppendLine("; Add hardware register definitions for your platform here.");
		return sb.ToString();
	}
}
