using Pansy.Core;

namespace Peony.Core;

/// <summary>
/// Exports symbol/label data to various formats for use with other tools
/// </summary>
public static class SymbolExporter {
	/// <summary>
	/// Export symbols to a file in the specified format
	/// </summary>
	public static void Export(DisassemblyResult result, string outputPath, SymbolFormat format) {
		// Pansy is binary, handle separately
		if (format == SymbolFormat.Pansy) {
			ExportPansy(result, outputPath);
			return;
		}

		var content = format switch {
			SymbolFormat.Mesen => ExportMesen(result),
			SymbolFormat.FCEUX => ExportFCEUX(result),
			SymbolFormat.NoGlasses => ExportNoGlasses(result),
			SymbolFormat.Ca65Debug => ExportCa65Debug(result),
			SymbolFormat.Wla => ExportWla(result),
			SymbolFormat.BizHawk => ExportBizHawk(result),
			_ => throw new ArgumentException($"Unsupported symbol format: {format}")
		};

		File.WriteAllText(outputPath, content);
	}

	/// <summary>
	/// Export symbols to Mesen label format (.mlb)
	/// Format: TYPE:ADDRESS:LABEL or TYPE:STARTADDRESS-ENDADDRESS:LABEL
	/// Where TYPE is: P=PRG, W=Work RAM, S=Save RAM, R=Register, G=Internal RAM (NES), O=OAM
	/// </summary>
	public static string ExportMesen(DisassemblyResult result) {
		var sb = new System.Text.StringBuilder();

		// Export global labels as PRG ROM labels
		foreach (var kvp in result.Labels.OrderBy(x => x.Key)) {
			var address = kvp.Key;
			var label = SanitizeLabel(kvp.Value);

			// Determine label type based on address range
			var type = GetMesenLabelType(address);
			sb.AppendLine($"{type}:{address:x4}:{label}");
		}

		// Export bank-specific labels
		foreach (var kvp in result.BankLabels.OrderBy(x => x.Key.Bank).ThenBy(x => x.Key.Address)) {
			var (address, bank) = kvp.Key;
			var label = SanitizeLabel(kvp.Value);

			// Bank-specific labels use the full address with bank offset
			// For NES: PRG banks are 16KB each
			var fullAddress = address + (uint)(bank * 0x4000);
			sb.AppendLine($"P:{fullAddress:x}:{label}");
		}

		// Export comments if available
		foreach (var kvp in result.Comments.OrderBy(x => x.Key)) {
			var address = kvp.Key;
			var comment = EscapeComment(kvp.Value);
			var type = GetMesenLabelType(address);
			// Mesen uses :Comment suffix
			sb.AppendLine($"{type}:{address:x4}::{comment}");
		}

		return sb.ToString();
	}

	/// <summary>
	/// Export symbols to FCEUX name list format (.nl)
	/// Format: $ADDRESS#LABEL#COMMENT
	/// </summary>
	public static string ExportFCEUX(DisassemblyResult result) {
		var sb = new System.Text.StringBuilder();

		// Combine labels and comments
		var allAddresses = result.Labels.Keys
			.Concat(result.Comments.Keys)
			.Distinct()
			.OrderBy(a => a);

		foreach (var address in allAddresses) {
			var label = result.Labels.TryGetValue(address, out var l) ? SanitizeLabel(l) : "";
			var comment = result.Comments.TryGetValue(address, out var c) ? c : "";

			sb.AppendLine($"${address:x4}#{label}#{comment}");
		}

		// Bank-specific labels with bank suffix
		foreach (var kvp in result.BankLabels.OrderBy(x => x.Key.Bank).ThenBy(x => x.Key.Address)) {
			var (address, bank) = kvp.Key;
			var label = SanitizeLabel(kvp.Value);
			sb.AppendLine($"${address:x4}#{label}_bank{bank}#Bank {bank}");
		}

		return sb.ToString();
	}

	/// <summary>
	/// Export symbols to No$gba/No$sns symbol format (.sym)
	/// Format: ADDRESS LABEL
	/// Supports bank:offset notation for multi-bank ROMs
	/// </summary>
	public static string ExportNoGlasses(DisassemblyResult result) {
		var sb = new System.Text.StringBuilder();

		sb.AppendLine("; No$gba/No$sns Symbol File");
		sb.AppendLine("; Generated by Peony Disassembler");
		sb.AppendLine();

		// Global labels
		foreach (var kvp in result.Labels.OrderBy(x => x.Key)) {
			var address = kvp.Key;
			var label = SanitizeLabel(kvp.Value);
			sb.AppendLine($"{address:x8} {label}");
		}

		// Bank-specific labels (use bank:offset format)
		foreach (var kvp in result.BankLabels.OrderBy(x => x.Key.Bank).ThenBy(x => x.Key.Address)) {
			var (address, bank) = kvp.Key;
			var label = SanitizeLabel(kvp.Value);
			sb.AppendLine($"{bank:x2}:{address:x4} {label}");
		}

		return sb.ToString();
	}

	/// <summary>
	/// Export symbols to ca65 debug format (.dbg)
	/// This is a simplified export that generates a .dbg file compatible with cc65 tools
	/// </summary>
	public static string ExportCa65Debug(DisassemblyResult result) {
		var sb = new System.Text.StringBuilder();

		sb.AppendLine("version\tmajor=2,minor=0");
		sb.AppendLine();
		sb.AppendLine("info\tcsym=0,file=1,lib=0,line=0,mod=1,scope=1,seg=1,span=0,sym=0,type=0");
		sb.AppendLine();

		// File section
		sb.AppendLine($"file\tid=0,name=\"disassembly.s\",size=0,mtime=0,mod=0");
		sb.AppendLine();

		// Module section
		sb.AppendLine($"mod\tid=0,name=\"disassembly.o\",file=0");
		sb.AppendLine();

		// Segment section
		sb.AppendLine($"seg\tid=0,name=\"CODE\",start=0x{result.RomInfo.Metadata.GetValueOrDefault("EntryPoint", "8000")},size={result.RomInfo.Size},addrsize=absolute,type=ro,oname=\"ROM\",ooffs=0");
		sb.AppendLine();

		// Scope section
		sb.AppendLine("scope\tid=0,name=\"\",mod=0,type=scope,size=0,parent=0");
		sb.AppendLine();

		// Labels as symbols
		int symId = 0;
		foreach (var kvp in result.Labels.OrderBy(x => x.Key)) {
			var address = kvp.Key;
			var label = SanitizeLabel(kvp.Value);
			sb.AppendLine($"sym\tid={symId},name=\"{label}\",addrsize=absolute,scope=0,def=0,ref=0,val=0x{address:x},seg=0,type=lab");
			symId++;
		}

		return sb.ToString();
	}

	/// <summary>
	/// Export symbols to WLA-DX symbol format (.sym)
	/// Format: [labels] section with ADDRESS LABEL entries
	/// </summary>
	public static string ExportWla(DisassemblyResult result) {
		var sb = new System.Text.StringBuilder();

		sb.AppendLine("; WLA-DX Symbol File");
		sb.AppendLine("; Generated by Peony Disassembler");
		sb.AppendLine();

		sb.AppendLine("[labels]");

		// Bank-specific format: bank:address label
		if (result.BankLabels.Count > 0) {
			foreach (var kvp in result.BankLabels.OrderBy(x => x.Key.Bank).ThenBy(x => x.Key.Address)) {
				var (address, bank) = kvp.Key;
				var label = SanitizeLabel(kvp.Value);
				sb.AppendLine($"{bank:x2}:{address:x4} {label}");
			}
		}

		// Global labels (bank 0 or unbanked)
		foreach (var kvp in result.Labels.OrderBy(x => x.Key)) {
			var address = kvp.Key;
			var label = SanitizeLabel(kvp.Value);
			sb.AppendLine($"00:{address:x4} {label}");
		}

		return sb.ToString();
	}

	/// <summary>
	/// Export symbols to BizHawk .cht format (compatible with RAM Watch/Cheats)
	/// Also useful for FCEUX cheat format
	/// </summary>
	public static string ExportBizHawk(DisassemblyResult result) {
		var sb = new System.Text.StringBuilder();

		sb.AppendLine("; BizHawk Symbol File");
		sb.AppendLine("; Generated by Peony Disassembler");
		sb.AppendLine();

		// Export RAM labels (addresses < 0x8000 typically)
		foreach (var kvp in result.Labels.Where(x => x.Key < 0x8000).OrderBy(x => x.Key)) {
			var address = kvp.Key;
			var label = SanitizeLabel(kvp.Value);
			sb.AppendLine($"0x{address:x4}\t{label}");
		}

		sb.AppendLine();
		sb.AppendLine("; ROM Labels");

		// ROM labels
		foreach (var kvp in result.Labels.Where(x => x.Key >= 0x8000).OrderBy(x => x.Key)) {
			var address = kvp.Key;
			var label = SanitizeLabel(kvp.Value);
			sb.AppendLine($"0x{address:x4}\t{label}");
		}

		return sb.ToString();
	}

	#region Pansy Export

	/// <summary>
	/// Export disassembly result to Pansy binary format (.pansy).
	/// Uses Pansy.Core.PansyWriter for spec-compliant file generation.
	/// Includes all available sections: code/data map, symbols, comments,
	/// memory regions, cross-references, and metadata.
	/// </summary>
	public static void ExportPansy(DisassemblyResult result, string outputPath) {
		var writer = new PansyWriter {
			Platform = GetPansyPlatformId(result.RomInfo),
			RomSize = (uint)(result.RomInfo?.Size ?? 0),
			EnableCompression = true,
			ProjectName = result.RomInfo?.Platform ?? "",
			ProjectVersion = "1.0",
		};

		// Add symbols from global labels
		foreach (var (address, name) in result.Labels) {
			writer.AddSymbol(address, name, DetectPansySymbolType(address, name, result));
		}

		// Add bank-specific labels (encode bank in high byte of address)
		foreach (var ((address, bank), name) in result.BankLabels) {
			var addr24 = (uint)((bank << 16) | (int)address);
			writer.AddSymbol(addr24, name, SymbolType.Label);
		}

		// Add comments
		foreach (var (address, text) in result.Comments) {
			writer.AddComment(address, text, (byte)CommentType.Inline);
		}

		// Add code/data map from disassembly blocks
		PopulateCodeDataMap(writer, result);

		// Add cross-references
		foreach (var (targetAddress, refs) in result.CrossReferences) {
			foreach (var xref in refs) {
				var pansyType = MapCrossRefType(xref.Type);
				writer.AddCrossReference(new CrossReference(xref.FromAddress, targetAddress, pansyType));
			}
		}

		// Add memory regions from disassembly blocks
		AddMemoryRegions(writer, result);

		// Generate and write the file
		var data = writer.Generate();
		File.WriteAllBytes(outputPath, data);
	}

	/// <summary>
	/// Map platform name to Pansy platform ID.
	/// </summary>
	private static byte GetPansyPlatformId(RomInfo? info) {
		if (info?.Platform == null) return PansyLoader.PLATFORM_CUSTOM;

		return info.Platform.ToLowerInvariant() switch {
			"nes" => PansyLoader.PLATFORM_NES,
			"snes" or "super nintendo" => PansyLoader.PLATFORM_SNES,
			"gb" or "game boy" or "gameboy" => PansyLoader.PLATFORM_GB,
			"gba" or "game boy advance" => PansyLoader.PLATFORM_GBA,
			"genesis" or "mega drive" => PansyLoader.PLATFORM_GENESIS,
			"sms" or "master system" => PansyLoader.PLATFORM_SMS,
			"pce" or "turbografx" or "pc engine" => PansyLoader.PLATFORM_PCE,
			"atari 2600" or "atari2600" or "2600" => PansyLoader.PLATFORM_ATARI_2600,
			"lynx" or "atari lynx" => PansyLoader.PLATFORM_LYNX,
			"wonderswan" or "ws" => PansyLoader.PLATFORM_WONDERSWAN,
			"neogeo" or "neo geo" => PansyLoader.PLATFORM_NEOGEO,
			"spc700" or "spc" => PansyLoader.PLATFORM_SPC700,
			"c64" or "commodore 64" => PansyLoader.PLATFORM_C64,
			"msx" => PansyLoader.PLATFORM_MSX,
			"atari 7800" or "7800" => PansyLoader.PLATFORM_ATARI_7800,
			"atari 8-bit" or "a8" => PansyLoader.PLATFORM_ATARI_8BIT,
			"apple ii" or "apple2" => PansyLoader.PLATFORM_APPLE_II,
			"zx spectrum" or "spectrum" => PansyLoader.PLATFORM_ZX_SPECTRUM,
			"colecovision" or "coleco" => PansyLoader.PLATFORM_COLECO,
			"intellivision" or "intv" => PansyLoader.PLATFORM_INTELLIVISION,
			"vectrex" => PansyLoader.PLATFORM_VECTREX,
			"game gear" or "gg" => PansyLoader.PLATFORM_GAMEGEAR,
			"32x" or "sega 32x" => PansyLoader.PLATFORM_32X,
			"sega cd" or "segacd" => PansyLoader.PLATFORM_SEGACD,
			"virtual boy" or "vb" => PansyLoader.PLATFORM_VIRTUALBOY,
			"amstrad cpc" or "cpc" => PansyLoader.PLATFORM_AMSTRAD_CPC,
			"bbc micro" or "bbc" => PansyLoader.PLATFORM_BBC_MICRO,
			"vic-20" or "vic20" => PansyLoader.PLATFORM_VIC20,
			"plus/4" or "plus4" => PansyLoader.PLATFORM_PLUS4,
			"c128" or "commodore 128" => PansyLoader.PLATFORM_C128,
			_ => PansyLoader.PLATFORM_CUSTOM
		};
	}

	/// <summary>
	/// Detect Pansy symbol type from disassembly context.
	/// </summary>
	private static SymbolType DetectPansySymbolType(uint address, string name, DisassemblyResult result) {
		var nameLower = name.ToLowerInvariant();

		// Check if this is an interrupt vector
		if (nameLower.Contains("nmi") || nameLower.Contains("irq") || nameLower.Contains("reset") ||
			nameLower.Contains("interrupt") || nameLower.Contains("brk") || nameLower.Contains("cop") ||
			nameLower.Contains("abort")) {
			return SymbolType.InterruptVector;
		}

		// Check if this is a subroutine entry point (has JSR/CALL cross-refs)
		if (result.CrossReferences.TryGetValue(address, out var refs)) {
			if (refs.Any(r => r.Type == CrossRefType.Call)) {
				return SymbolType.Function;
			}
		}

		// Check if address is in zero page / RAM area (likely a constant)
		if (address < 0x100 && nameLower.StartsWith("zp_")) {
			return SymbolType.Constant;
		}

		// Check for local label patterns
		if (name.StartsWith('.') || name.StartsWith('@') || name.StartsWith('+') || name.StartsWith('-')) {
			return SymbolType.Local;
		}

		return SymbolType.Label;
	}

	/// <summary>
	/// Map Peony CrossRefType to Pansy CrossRefType.
	/// </summary>
	private static Pansy.Core.CrossRefType MapCrossRefType(CrossRefType type) {
		return type switch {
			CrossRefType.Call => Pansy.Core.CrossRefType.Jsr,
			CrossRefType.Jump => Pansy.Core.CrossRefType.Jmp,
			CrossRefType.Branch => Pansy.Core.CrossRefType.Branch,
			CrossRefType.DataRef => Pansy.Core.CrossRefType.Read,
			CrossRefType.Pointer => Pansy.Core.CrossRefType.Read,
			_ => Pansy.Core.CrossRefType.Read,
		};
	}

	/// <summary>
	/// Populate the PansyWriter code/data map from disassembly blocks.
	/// Uses proper Pansy CDL flags: CODE=0x01, DATA=0x02, OPCODE=0x10, etc.
	/// </summary>
	private static void PopulateCodeDataMap(PansyWriter writer, DisassemblyResult result) {
		if (result.RomInfo?.Size == null || result.RomInfo.Size == 0)
			return;

		foreach (var block in result.Blocks) {
			foreach (var line in block.Lines) {
				var offset = GetRomOffset(line.Address, result.RomInfo);
				if (offset < 0 || offset >= result.RomInfo.Size) continue;

				if (block.Type == MemoryRegion.Code) {
					for (var i = 0; i < line.Bytes.Length && offset + i < result.RomInfo.Size; i++) {
						var addr = (uint)(offset + i);
						writer.MarkAsCode(addr);
						if (i == 0) {
							writer.MarkAsOpcode(addr);
						}
					}
				} else if (block.Type == MemoryRegion.Data || block.Type == MemoryRegion.Graphics ||
						   block.Type == MemoryRegion.Audio) {
					for (var i = 0; i < line.Bytes.Length && offset + i < result.RomInfo.Size; i++) {
						writer.MarkAsData((uint)(offset + i));
					}
				}
			}
		}

		// Mark jump targets and subroutine entry points from cross-references
		foreach (var (targetAddress, refs) in result.CrossReferences) {
			var offset = GetRomOffset(targetAddress, result.RomInfo);
			if (offset < 0 || offset >= result.RomInfo.Size) continue;

			foreach (var xref in refs) {
				if (xref.Type == CrossRefType.Jump || xref.Type == CrossRefType.Branch) {
					writer.MarkAsJumpTarget((uint)offset);
				} else if (xref.Type == CrossRefType.Call) {
					writer.MarkAsSubroutine((uint)offset);
				}
			}
		}
	}

	/// <summary>
	/// Add memory regions derived from disassembly blocks.
	/// </summary>
	private static void AddMemoryRegions(PansyWriter writer, DisassemblyResult result) {
		// Collect contiguous regions from blocks
		foreach (var block in result.Blocks) {
			var regionType = MapMemoryRegionType(block.Type);
			if (regionType == 0) continue; // Skip unknown

			writer.AddMemoryRegion(new Pansy.Core.MemoryRegion(
				block.StartAddress,
				block.EndAddress,
				regionType,
				(byte)(block.Bank >= 0 ? block.Bank : 0),
				$"{block.Type}_{block.StartAddress:x4}"
			));
		}
	}

	/// <summary>
	/// Map Peony MemoryRegion enum to Pansy MemoryRegionType byte value.
	/// </summary>
	private static byte MapMemoryRegionType(MemoryRegion type) {
		return type switch {
			MemoryRegion.Code => (byte)MemoryRegionType.ROM,
			MemoryRegion.Data => (byte)MemoryRegionType.ROM,
			MemoryRegion.Graphics => (byte)MemoryRegionType.ROM,
			MemoryRegion.Audio => (byte)MemoryRegionType.ROM,
			MemoryRegion.Ram => (byte)MemoryRegionType.RAM,
			MemoryRegion.Rom => (byte)MemoryRegionType.ROM,
			MemoryRegion.Hardware => (byte)MemoryRegionType.IO,
			_ => 0,
		};
	}

	/// <summary>
	/// Convert CPU address to ROM file offset (platform-specific).
	/// </summary>
	private static int GetRomOffset(uint address, RomInfo info) {
		var platform = info.Platform?.ToLowerInvariant() ?? "";

		return platform switch {
			"nes" => (int)(address - 0x8000 + 16), // Account for 16-byte iNES header
			"snes" => ConvertSnesAddressToOffset(address, info),
			"gb" or "gameboy" or "game boy" => (int)address, // Usually 1:1 mapping
			"gba" or "game boy advance" => (int)(address - 0x08000000), // GBA ROM base
			_ => (int)address // Default: direct mapping
		};
	}

	/// <summary>
	/// Convert SNES CPU address to ROM offset based on mapping mode.
	/// </summary>
	private static int ConvertSnesAddressToOffset(uint address, RomInfo info) {
		var bank = (int)(address >> 16);
		var offset = (int)(address & 0xffff);

		// Check mapping mode from mapper name
		var isHiROM = info.Mapper?.Contains("HiROM", StringComparison.OrdinalIgnoreCase) == true;

		if (isHiROM) {
			// HiROM: banks $C0-$FF map linearly, $40-$7D mirror
			if (bank >= 0xC0) {
				return ((bank - 0xC0) * 0x10000) + offset;
			} else if (bank >= 0x40 && bank < 0x7E) {
				return ((bank - 0x40) * 0x10000) + offset;
			}
		} else {
			// LoROM: $8000-$FFFF of each bank, banks $80-$FF map to $00-$7F
			if (offset >= 0x8000) {
				var realBank = bank >= 0x80 ? bank - 0x80 : bank;
				return (realBank * 0x8000) + (offset - 0x8000);
			}
		}

		return (int)address; // Fallback
	}

	#endregion

	/// <summary>
	/// Determine Mesen label type based on address
	/// </summary>
	private static char GetMesenLabelType(uint address) {
		return address switch {
			< 0x0800 => 'G',  // Internal RAM (first 2KB mirrored)
			< 0x2000 => 'G',  // Internal RAM mirrors
			< 0x4000 => 'R',  // PPU registers
			< 0x4020 => 'R',  // APU/IO registers
			< 0x6000 => 'P',  // Expansion ROM
			< 0x8000 => 'S',  // Save RAM / Work RAM
			_ => 'P'          // PRG ROM
		};
	}

	/// <summary>
	/// Sanitize label for compatibility with symbol formats
	/// </summary>
	private static string SanitizeLabel(string label) {
		// Replace invalid characters with underscores
		var result = new System.Text.StringBuilder();
		foreach (var c in label) {
			if (char.IsLetterOrDigit(c) || c == '_' || c == '.') {
				result.Append(c);
			} else {
				result.Append('_');
			}
		}

		// Ensure label doesn't start with a digit
		if (result.Length > 0 && char.IsDigit(result[0])) {
			result.Insert(0, '_');
		}

		return result.ToString();
	}

	/// <summary>
	/// Escape comment for formats that support inline comments
	/// </summary>
	private static string EscapeComment(string comment) {
		return comment
			.Replace("\r", "")
			.Replace("\n", " ")
			.Replace("#", "")
			.Replace(":", "");
	}
}

/// <summary>
/// Supported symbol export formats
/// </summary>
public enum SymbolFormat {
	/// <summary>Mesen emulator (.mlb)</summary>
	Mesen,

	/// <summary>FCEUX emulator (.nl)</summary>
	FCEUX,

	/// <summary>No$gba/No$sns (.sym)</summary>
	NoGlasses,

	/// <summary>ca65 debug format (.dbg)</summary>
	Ca65Debug,

	/// <summary>WLA-DX assembler (.sym)</summary>
	Wla,

	/// <summary>BizHawk (.cht)</summary>
	BizHawk,

	/// <summary>Pansy metadata file (.pansy) - Poppy/Peony interchange</summary>
	Pansy
}
