using Pansy.Core;
using Peony.Core;
using Xunit;

namespace Peony.Core.Tests;

/// <summary>
/// Tests for SymbolExporter functionality
/// </summary>
[Collection("PlatformResolver")]
public class SymbolExporterTests {
	private static DisassemblyResult CreateTestResult() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("Test", 8192, null, new Dictionary<string, string>())
		};

		// Add some test labels
		result.Labels[0x8000] = "reset";
		result.Labels[0x8050] = "nmi_handler";
		result.Labels[0x80a0] = "main_loop";
		result.Labels[0x0000] = "zp_temp";
		result.Labels[0x0010] = "zp_ptr_lo";
		result.Labels[0x0011] = "zp_ptr_hi";
		result.Labels[0x6000] = "sram_save";
		result.Labels[0x2000] = "ppu_ctrl";

		// Add some comments
		result.Comments[0x8000] = "Entry point";
		result.Comments[0x8050] = "NMI interrupt handler";

		// Add bank-specific labels
		result.BankLabels[(0x8000, 0)] = "bank0_init";
		result.BankLabels[(0x8000, 1)] = "bank1_init";
		result.BankLabels[(0x8100, 1)] = "bank1_data";

		return result;
	}

	// ========== Mesen Format Tests ==========

	[Fact]
	public void ExportMesen_ContainsLabels() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportMesen(result);

		Assert.Contains("reset", output);
		Assert.Contains("nmi_handler", output);
		Assert.Contains("main_loop", output);
	}

	[Fact]
	public void ExportMesen_CorrectLabelTypes() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportMesen(result);

		// PRG ROM labels should use P:
		Assert.Contains("P:8000:reset", output);

		// Internal RAM should use G:
		Assert.Contains("G:0000:zp_temp", output);

		// PPU registers should use R:
		Assert.Contains("R:2000:ppu_ctrl", output);

		// Save RAM should use S:
		Assert.Contains("S:6000:sram_save", output);
	}

	[Fact]
	public void ExportMesen_IncludesComments() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportMesen(result);

		Assert.Contains("Entry point", output);
		Assert.Contains("NMI interrupt handler", output);
	}

	[Fact]
	public void ExportMesen_IncludesBankLabels() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportMesen(result);

		Assert.Contains("bank0_init", output);
		Assert.Contains("bank1_init", output);
	}

	// ========== FCEUX Format Tests ==========

	[Fact]
	public void ExportFCEUX_CorrectFormat() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportFCEUX(result);

		// Format: $ADDRESS#LABEL#COMMENT
		Assert.Contains("$8000#reset#Entry point", output);
		Assert.Contains("$8050#nmi_handler#NMI interrupt handler", output);
	}

	[Fact]
	public void ExportFCEUX_HandlesEmptyComments() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportFCEUX(result);

		// Labels without comments should have empty comment field
		Assert.Contains("$80a0#main_loop#", output);
	}

	[Fact]
	public void ExportFCEUX_IncludesBankLabels() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportFCEUX(result);

		Assert.Contains("bank0_init_bank0", output);
		Assert.Contains("bank1_init_bank1", output);
	}

	// ========== No$gba Format Tests ==========

	[Fact]
	public void ExportNoGlasses_ContainsHeader() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportNoGlasses(result);

		Assert.Contains("No$gba/No$sns Symbol File", output);
		Assert.Contains("Generated by Peony", output);
	}

	[Fact]
	public void ExportNoGlasses_CorrectFormat() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportNoGlasses(result);

		// Format: ADDRESS LABEL
		Assert.Contains("00008000 reset", output);
	}

	[Fact]
	public void ExportNoGlasses_BankFormat() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportNoGlasses(result);

		// Bank format: bank:offset label
		Assert.Contains("00:8000 bank0_init", output);
		Assert.Contains("01:8000 bank1_init", output);
	}

	// ========== ca65 Debug Format Tests ==========

	[Fact]
	public void ExportCa65Debug_ContainsVersion() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportCa65Debug(result);

		Assert.Contains("version\tmajor=2,minor=0", output);
	}

	[Fact]
	public void ExportCa65Debug_ContainsSymbols() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportCa65Debug(result);

		Assert.Contains("sym\t", output);
		Assert.Contains("name=\"reset\"", output);
		Assert.Contains("val=0x8000", output);
	}

	[Fact]
	public void ExportCa65Debug_ContainsSegments() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportCa65Debug(result);

		Assert.Contains("seg\tid=0,name=\"CODE\"", output);
	}

	// ========== WLA-DX Format Tests ==========

	[Fact]
	public void ExportWla_ContainsLabelsSection() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportWla(result);

		Assert.Contains("[labels]", output);
	}

	[Fact]
	public void ExportWla_BankFormat() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportWla(result);

		// Bank format: bank:address label
		Assert.Contains("00:8000 bank0_init", output);
		Assert.Contains("01:8000 bank1_init", output);
	}

	// ========== BizHawk Format Tests ==========

	[Fact]
	public void ExportBizHawk_SeparatesRamAndRomLabels() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportBizHawk(result);

		Assert.Contains("zp_temp", output);
		Assert.Contains("ROM Labels", output);
		Assert.Contains("reset", output);
	}

	[Fact]
	public void ExportBizHawk_CorrectFormat() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportBizHawk(result);

		// Format: 0xADDRESS\tLABEL
		Assert.Contains("0x0000\tzp_temp", output);
		Assert.Contains("0x8000\treset", output);
	}

	// ========== Label Sanitization Tests ==========

	[Fact]
	public void Export_SanitizesInvalidCharacters() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("Test", 8192, null, new Dictionary<string, string>())
		};
		result.Labels[0x8000] = "label-with-dash";
		result.Labels[0x8010] = "label with spaces";
		result.Labels[0x8020] = "123_starts_with_number";

		var output = SymbolExporter.ExportMesen(result);

		// Dashes should become underscores
		Assert.Contains("label_with_dash", output);
		// Spaces should become underscores
		Assert.Contains("label_with_spaces", output);
		// Numbers at start should get underscore prefix
		Assert.Contains("_123_starts_with_number", output);
	}

	// ========== Export Method Tests ==========

	[Fact]
	public void Export_WritesFile() {
		var result = CreateTestResult();
		var tempFile = Path.GetTempFileName();

		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Mesen);

			Assert.True(File.Exists(tempFile));
			var content = File.ReadAllText(tempFile);
			Assert.Contains("reset", content);
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void Export_AllFormatsSucceed() {
		var result = CreateTestResult();
		var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
		Directory.CreateDirectory(tempDir);

		try {
			foreach (var format in Enum.GetValues<SymbolFormat>()) {
				var tempFile = Path.Combine(tempDir, $"test.{format.ToString().ToLower()}");
				SymbolExporter.Export(result, tempFile, format);
				Assert.True(File.Exists(tempFile), $"Failed to export {format}");
			}
		} finally {
			Directory.Delete(tempDir, true);
		}
	}

	// ========== Pansy Format Tests ==========

	[Fact]
	public void ExportPansy_CreatesValidBinaryFile() {
		var result = CreateTestResult();
		// Set a proper platform for Pansy export
		result.RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>());

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);

			Assert.True(File.Exists(tempFile));
			var data = File.ReadAllBytes(tempFile);

			// Verify magic
			Assert.True(data.Length >= 32, "File too small for header");
			Assert.Equal((byte)'P', data[0]);
			Assert.Equal((byte)'A', data[1]);
			Assert.Equal((byte)'N', data[2]);
			Assert.Equal((byte)'S', data[3]);
			Assert.Equal((byte)'Y', data[4]);
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_CanBeLoadedByPansyLoader() {
		var result = CreateTestResult();
		result.RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>());

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);

			// Load with PansyLoader and verify data
			var loader = new PansyLoader(data);

			Assert.Equal(PansyLoader.PLATFORM_NES, loader.Platform);
			Assert.Equal(8192u, loader.RomSize);
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_ContainsSymbols() {
		// Use a result without conflicting bank labels at same addresses
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>())
		};
		result.Labels[0x8000] = "reset";
		result.Labels[0x8050] = "nmi_handler";

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);

			var loader = new PansyLoader(data);

			// Check symbols were imported
			Assert.Equal("reset", loader.GetSymbol(0x8000));
			Assert.Equal("nmi_handler", loader.GetSymbol(0x8050));
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_ContainsComments() {
		var result = CreateTestResult();
		result.RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>());

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);

			var loader = new PansyLoader(data);

			// Check comments were imported
			Assert.Equal("Entry point", loader.GetComment(0x8000));
			Assert.Equal("NMI interrupt handler", loader.GetComment(0x8050));
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_DetectsPlatformFromRomInfo() {
		var snesResult = new DisassemblyResult {
			RomInfo = new RomInfo("SNES", 32768, "LoROM", new Dictionary<string, string>())
		};

		var gbResult = new DisassemblyResult {
			RomInfo = new RomInfo("Game Boy", 16384, "MBC1", new Dictionary<string, string>())
		};

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(snesResult, tempFile, SymbolFormat.Pansy);
			var snesLoader = new PansyLoader(File.ReadAllBytes(tempFile));
			Assert.Equal(PansyLoader.PLATFORM_SNES, snesLoader.Platform);

			SymbolExporter.Export(gbResult, tempFile, SymbolFormat.Pansy);
			var gbLoader = new PansyLoader(File.ReadAllBytes(tempFile));
			Assert.Equal(PansyLoader.PLATFORM_GB, gbLoader.Platform);
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_CompressedFlag_IsSet() {
		var result = CreateTestResult();
		result.RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>());

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);

			// Flags at offset 10 (2 bytes LE)
			var flags = BitConverter.ToUInt16(data, 10);
			Assert.Equal(1, flags & 1); // Compressed flag should be set
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_CrossReferences_AreExported() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>())
		};
		result.Labels[0x8000] = "reset";
		result.Labels[0x8100] = "subroutine";

		// Add cross-references
		result.CrossReferences[0x8100] = [
			new CrossRef(0x8010, 0, CrossRefType.Call),
			new CrossRef(0x8020, 0, CrossRefType.Jump),
		];

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);
			var loader = new PansyLoader(data);

			// Verify cross-references were loaded
			var crossRefs = loader.CrossReferences;
			Assert.NotNull(crossRefs);
			Assert.True(crossRefs.Count >= 2, $"Expected >= 2 cross-refs, got {crossRefs.Count}");
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_CrossRefTypeMapping_IsCorrect() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>())
		};

		// Add cross-references of different types
		result.CrossReferences[0x8100] = [
			new CrossRef(0x8010, 0, CrossRefType.Call),    // → Jsr (1)
			new CrossRef(0x8020, 0, CrossRefType.Jump),    // → Jmp (2)
			new CrossRef(0x8030, 0, CrossRefType.Branch),  // → Branch (3)
			new CrossRef(0x8040, 0, CrossRefType.DataRef), // → Read (4)
			new CrossRef(0x8050, 0, CrossRefType.Pointer), // → Read (4)
		];

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);
			var loader = new PansyLoader(data);

			var crossRefs = loader.CrossReferences;
			Assert.Equal(5, crossRefs.Count);

			// Verify type mappings
			var byType = crossRefs.GroupBy(x => x.Type).ToDictionary(g => g.Key, g => g.Count());
			Assert.True(byType.ContainsKey(Pansy.Core.CrossRefType.Jsr), "Should have Jsr cross-ref");
			Assert.True(byType.ContainsKey(Pansy.Core.CrossRefType.Jmp), "Should have Jmp cross-ref");
			Assert.True(byType.ContainsKey(Pansy.Core.CrossRefType.Branch), "Should have Branch cross-ref");
			Assert.True(byType.ContainsKey(Pansy.Core.CrossRefType.Read), "Should have Read cross-ref");
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_MemoryRegions_AreExported() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>())
		};

		// Add code blocks that become memory regions
		result.Blocks.Add(new DisassembledBlock(
			0x8000, 0x80ff, Peony.Core.MemoryRegion.Code,
			[new DisassembledLine(0x8000, [0xa9, 0x00], null, "lda #$00", null)]
		));

		result.Blocks.Add(new DisassembledBlock(
			0x8100, 0x81ff, Peony.Core.MemoryRegion.Data,
			[new DisassembledLine(0x8100, [0xff], null, ".db $ff", null)]
		));

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);
			var loader = new PansyLoader(data);

			var regions = loader.MemoryRegions;
			Assert.NotNull(regions);
			Assert.True(regions.Count >= 2, $"Expected >= 2 memory regions, got {regions.Count}");
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_Metadata_IsExported() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>())
		};
		result.Labels[0x8000] = "reset";

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);
			var loader = new PansyLoader(data);

			// Metadata section should be present
			Assert.NotNull(loader.ProjectName);
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_SymbolTypes_AreDetected() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>())
		};

		// Interrupt vector names should be detected
		result.Labels[0xfffa] = "nmi_handler";
		result.Labels[0xfffc] = "reset_vector";
		result.Labels[0xfffe] = "irq_handler";

		// Regular label
		result.Labels[0x8050] = "main_loop";

		// Local label pattern
		result.Labels[0x8060] = ".loop";

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);
			var loader = new PansyLoader(data);

			// Check that interrupt vectors were detected
			var nmiEntry = loader.GetSymbolEntry((int)0xfffa);
			Assert.NotNull(nmiEntry);
			Assert.Equal(SymbolType.InterruptVector, nmiEntry.Type);

			var resetEntry = loader.GetSymbolEntry((int)0xfffc);
			Assert.NotNull(resetEntry);
			Assert.Equal(SymbolType.InterruptVector, resetEntry.Type);

			// Local label
			var localEntry = loader.GetSymbolEntry(0x8060);
			Assert.NotNull(localEntry);
			Assert.Equal(SymbolType.Local, localEntry.Type);

			// Regular label
			var mainEntry = loader.GetSymbolEntry(0x8050);
			Assert.NotNull(mainEntry);
			Assert.Equal(SymbolType.Label, mainEntry.Type);
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_FunctionDetection_FromCrossRefs() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>())
		};

		result.Labels[0x8100] = "my_function";

		// Cross-ref of type Call pointing to 0x8100
		result.CrossReferences[0x8100] = [
			new CrossRef(0x8010, 0, CrossRefType.Call),
		];

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);
			var loader = new PansyLoader(data);

			var funcEntry = loader.GetSymbolEntry(0x8100);
			Assert.NotNull(funcEntry);
			Assert.Equal(SymbolType.Function, funcEntry.Type);
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_CommentType_IsInline() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>())
		};
		result.Comments[0x8000] = "This is a comment";

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);
			var loader = new PansyLoader(data);

			var commentEntry = loader.GetCommentEntry(0x8000);
			Assert.NotNull(commentEntry);
			Assert.Equal(CommentType.Inline, commentEntry.Type);
			Assert.Equal("This is a comment", commentEntry.Text);
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_AllPlatformIds_AreCorrect() {
		var platformTests = new Dictionary<string, byte> {
			["NES"] = PansyLoader.PLATFORM_NES,
			["SNES"] = PansyLoader.PLATFORM_SNES,
			["Game Boy"] = PansyLoader.PLATFORM_GB,
			["Game Boy Advance"] = PansyLoader.PLATFORM_GBA,
			["Genesis"] = PansyLoader.PLATFORM_GENESIS,
			["Master System"] = PansyLoader.PLATFORM_SMS,
			["Atari 2600"] = PansyLoader.PLATFORM_ATARI_2600,
			["Lynx"] = PansyLoader.PLATFORM_LYNX,
			["WonderSwan"] = PansyLoader.PLATFORM_WONDERSWAN,
		};

		var tempFile = Path.GetTempFileName();
		try {
			foreach (var (platform, expectedId) in platformTests) {
				var result = new DisassemblyResult {
					RomInfo = new RomInfo(platform, 1024, null, new Dictionary<string, string>())
				};

				SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
				var data = File.ReadAllBytes(tempFile);
				var loader = new PansyLoader(data);

				Assert.Equal(expectedId, loader.Platform);
			}
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_UnknownPlatform_UsesCustomId() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("UnknownSystem", 1024, null, new Dictionary<string, string>())
		};

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);
			var loader = new PansyLoader(data);

			Assert.Equal(PansyLoader.PLATFORM_CUSTOM, loader.Platform);
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_SectionCount_IncludesAllSections() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>())
		};
		result.Labels[0x8000] = "reset";
		result.Comments[0x8000] = "Entry point";
		result.CrossReferences[0x8000] = [
			new CrossRef(0x8010, 0, CrossRefType.Call),
		];
		result.Blocks.Add(new DisassembledBlock(
			0x8000, 0x80ff, Peony.Core.MemoryRegion.Code,
			[new DisassembledLine(0x8000, [0xa9, 0x00], null, "lda #$00", null)]
		));

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);

			// Section count at offset 24
			var sectionCount = BitConverter.ToUInt32(data, 24);

			// Should have: code_data_map, symbols, comments, memory_regions, cross_refs, metadata
			Assert.True(sectionCount >= 5, $"Expected >= 5 sections, got {sectionCount}");
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_Version_Is0x0100() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>())
		};

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);

			// Version at offset 8 (2 bytes LE)
			var version = BitConverter.ToUInt16(data, 8);
			Assert.Equal(0x0100, version);
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_RomSize_IsPreserved() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("NES", 32768, "NROM", new Dictionary<string, string>())
		};

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);

			// ROM size at offset 16 (4 bytes LE)
			var romSize = BitConverter.ToUInt32(data, 16);
			Assert.Equal(32768u, romSize);
		} finally {
			File.Delete(tempFile);
		}
	}
}
