using Pansy.Core;
using Peony.Core;
using Xunit;

namespace Peony.Core.Tests;

/// <summary>
/// Tests for SymbolExporter functionality
/// </summary>
public class SymbolExporterTests {
	private static DisassemblyResult CreateTestResult() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("Test", 8192, null, new Dictionary<string, string>())
		};

		// Add some test labels
		result.Labels[0x8000] = "reset";
		result.Labels[0x8050] = "nmi_handler";
		result.Labels[0x80a0] = "main_loop";
		result.Labels[0x0000] = "zp_temp";
		result.Labels[0x0010] = "zp_ptr_lo";
		result.Labels[0x0011] = "zp_ptr_hi";
		result.Labels[0x6000] = "sram_save";
		result.Labels[0x2000] = "ppu_ctrl";

		// Add some comments
		result.Comments[0x8000] = "Entry point";
		result.Comments[0x8050] = "NMI interrupt handler";

		// Add bank-specific labels
		result.BankLabels[(0x8000, 0)] = "bank0_init";
		result.BankLabels[(0x8000, 1)] = "bank1_init";
		result.BankLabels[(0x8100, 1)] = "bank1_data";

		return result;
	}

	// ========== Mesen Format Tests ==========

	[Fact]
	public void ExportMesen_ContainsLabels() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportMesen(result);

		Assert.Contains("reset", output);
		Assert.Contains("nmi_handler", output);
		Assert.Contains("main_loop", output);
	}

	[Fact]
	public void ExportMesen_CorrectLabelTypes() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportMesen(result);

		// PRG ROM labels should use P:
		Assert.Contains("P:8000:reset", output);

		// Internal RAM should use G:
		Assert.Contains("G:0000:zp_temp", output);

		// PPU registers should use R:
		Assert.Contains("R:2000:ppu_ctrl", output);

		// Save RAM should use S:
		Assert.Contains("S:6000:sram_save", output);
	}

	[Fact]
	public void ExportMesen_IncludesComments() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportMesen(result);

		Assert.Contains("Entry point", output);
		Assert.Contains("NMI interrupt handler", output);
	}

	[Fact]
	public void ExportMesen_IncludesBankLabels() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportMesen(result);

		Assert.Contains("bank0_init", output);
		Assert.Contains("bank1_init", output);
	}

	// ========== FCEUX Format Tests ==========

	[Fact]
	public void ExportFCEUX_CorrectFormat() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportFCEUX(result);

		// Format: $ADDRESS#LABEL#COMMENT
		Assert.Contains("$8000#reset#Entry point", output);
		Assert.Contains("$8050#nmi_handler#NMI interrupt handler", output);
	}

	[Fact]
	public void ExportFCEUX_HandlesEmptyComments() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportFCEUX(result);

		// Labels without comments should have empty comment field
		Assert.Contains("$80a0#main_loop#", output);
	}

	[Fact]
	public void ExportFCEUX_IncludesBankLabels() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportFCEUX(result);

		Assert.Contains("bank0_init_bank0", output);
		Assert.Contains("bank1_init_bank1", output);
	}

	// ========== No$gba Format Tests ==========

	[Fact]
	public void ExportNoGlasses_ContainsHeader() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportNoGlasses(result);

		Assert.Contains("No$gba/No$sns Symbol File", output);
		Assert.Contains("Generated by Peony", output);
	}

	[Fact]
	public void ExportNoGlasses_CorrectFormat() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportNoGlasses(result);

		// Format: ADDRESS LABEL
		Assert.Contains("00008000 reset", output);
	}

	[Fact]
	public void ExportNoGlasses_BankFormat() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportNoGlasses(result);

		// Bank format: bank:offset label
		Assert.Contains("00:8000 bank0_init", output);
		Assert.Contains("01:8000 bank1_init", output);
	}

	// ========== ca65 Debug Format Tests ==========

	[Fact]
	public void ExportCa65Debug_ContainsVersion() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportCa65Debug(result);

		Assert.Contains("version\tmajor=2,minor=0", output);
	}

	[Fact]
	public void ExportCa65Debug_ContainsSymbols() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportCa65Debug(result);

		Assert.Contains("sym\t", output);
		Assert.Contains("name=\"reset\"", output);
		Assert.Contains("val=0x8000", output);
	}

	[Fact]
	public void ExportCa65Debug_ContainsSegments() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportCa65Debug(result);

		Assert.Contains("seg\tid=0,name=\"CODE\"", output);
	}

	// ========== WLA-DX Format Tests ==========

	[Fact]
	public void ExportWla_ContainsLabelsSection() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportWla(result);

		Assert.Contains("[labels]", output);
	}

	[Fact]
	public void ExportWla_BankFormat() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportWla(result);

		// Bank format: bank:address label
		Assert.Contains("00:8000 bank0_init", output);
		Assert.Contains("01:8000 bank1_init", output);
	}

	// ========== BizHawk Format Tests ==========

	[Fact]
	public void ExportBizHawk_SeparatesRamAndRomLabels() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportBizHawk(result);

		Assert.Contains("zp_temp", output);
		Assert.Contains("ROM Labels", output);
		Assert.Contains("reset", output);
	}

	[Fact]
	public void ExportBizHawk_CorrectFormat() {
		var result = CreateTestResult();
		var output = SymbolExporter.ExportBizHawk(result);

		// Format: 0xADDRESS\tLABEL
		Assert.Contains("0x0000\tzp_temp", output);
		Assert.Contains("0x8000\treset", output);
	}

	// ========== Label Sanitization Tests ==========

	[Fact]
	public void Export_SanitizesInvalidCharacters() {
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("Test", 8192, null, new Dictionary<string, string>())
		};
		result.Labels[0x8000] = "label-with-dash";
		result.Labels[0x8010] = "label with spaces";
		result.Labels[0x8020] = "123_starts_with_number";

		var output = SymbolExporter.ExportMesen(result);

		// Dashes should become underscores
		Assert.Contains("label_with_dash", output);
		// Spaces should become underscores
		Assert.Contains("label_with_spaces", output);
		// Numbers at start should get underscore prefix
		Assert.Contains("_123_starts_with_number", output);
	}

	// ========== Export Method Tests ==========

	[Fact]
	public void Export_WritesFile() {
		var result = CreateTestResult();
		var tempFile = Path.GetTempFileName();

		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Mesen);

			Assert.True(File.Exists(tempFile));
			var content = File.ReadAllText(tempFile);
			Assert.Contains("reset", content);
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void Export_AllFormatsSucceed() {
		var result = CreateTestResult();
		var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
		Directory.CreateDirectory(tempDir);

		try {
			foreach (var format in Enum.GetValues<SymbolFormat>()) {
				var tempFile = Path.Combine(tempDir, $"test.{format.ToString().ToLower()}");
				SymbolExporter.Export(result, tempFile, format);
				Assert.True(File.Exists(tempFile), $"Failed to export {format}");
			}
		} finally {
			Directory.Delete(tempDir, true);
		}
	}

	// ========== Pansy Format Tests ==========

	[Fact]
	public void ExportPansy_CreatesValidBinaryFile() {
		var result = CreateTestResult();
		// Set a proper platform for Pansy export
		result.RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>());

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);

			Assert.True(File.Exists(tempFile));
			var data = File.ReadAllBytes(tempFile);

			// Verify magic
			Assert.True(data.Length >= 32, "File too small for header");
			Assert.Equal((byte)'P', data[0]);
			Assert.Equal((byte)'A', data[1]);
			Assert.Equal((byte)'N', data[2]);
			Assert.Equal((byte)'S', data[3]);
			Assert.Equal((byte)'Y', data[4]);
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_CanBeLoadedByPansyLoader() {
		var result = CreateTestResult();
		result.RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>());

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);

			// Load with PansyLoader and verify data
			var loader = new PansyLoader(data);

			Assert.Equal(PansyLoader.PLATFORM_NES, loader.Platform);
			Assert.Equal(8192u, loader.RomSize);
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_ContainsSymbols() {
		// Use a result without conflicting bank labels at same addresses
		var result = new DisassemblyResult {
			RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>())
		};
		result.Labels[0x8000] = "reset";
		result.Labels[0x8050] = "nmi_handler";

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);

			var loader = new PansyLoader(data);

			// Check symbols were imported
			Assert.Equal("reset", loader.GetSymbol(0x8000));
			Assert.Equal("nmi_handler", loader.GetSymbol(0x8050));
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_ContainsComments() {
		var result = CreateTestResult();
		result.RomInfo = new RomInfo("NES", 8192, "NROM", new Dictionary<string, string>());

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(result, tempFile, SymbolFormat.Pansy);
			var data = File.ReadAllBytes(tempFile);

			var loader = new PansyLoader(data);

			// Check comments were imported
			Assert.Equal("Entry point", loader.GetComment(0x8000));
			Assert.Equal("NMI interrupt handler", loader.GetComment(0x8050));
		} finally {
			File.Delete(tempFile);
		}
	}

	[Fact]
	public void ExportPansy_DetectsPlatformFromRomInfo() {
		var snesResult = new DisassemblyResult {
			RomInfo = new RomInfo("SNES", 32768, "LoROM", new Dictionary<string, string>())
		};

		var gbResult = new DisassemblyResult {
			RomInfo = new RomInfo("Game Boy", 16384, "MBC1", new Dictionary<string, string>())
		};

		var tempFile = Path.GetTempFileName();
		try {
			SymbolExporter.Export(snesResult, tempFile, SymbolFormat.Pansy);
			var snesLoader = new PansyLoader(File.ReadAllBytes(tempFile));
			Assert.Equal(PansyLoader.PLATFORM_SNES, snesLoader.Platform);

			SymbolExporter.Export(gbResult, tempFile, SymbolFormat.Pansy);
			var gbLoader = new PansyLoader(File.ReadAllBytes(tempFile));
			Assert.Equal(PansyLoader.PLATFORM_GB, gbLoader.Platform);
		} finally {
			File.Delete(tempFile);
		}
	}
}
